from __future__ import annotations

from collections.abc import Iterator
from contextlib import contextmanager
from functools import lru_cache
from typing import Annotated, Literal

from fastapi import Depends
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_prefix="MODELER_")

    tenancy_mode: Literal["saas-pooled", "cro-silo", "onprem-single"] = "saas-pooled"
    database_url: str = "postgresql+asyncpg://modeler:modeler@localhost:5432/modeler"
    # How campaigns and runs execute. "local" runs the single-node headless executor in-process (no Temporal
    # cluster needed — the permanent no-Docker path); "temporal" submits to a Temporal cluster (P2/P3 stack).
    execution_backend: Literal["local", "temporal"] = "local"
    temporal_address: str | None = None
    temporal_namespace: str = "default"
    object_store_uri: str = "s3://modeler-dev"
    results_root: str = ""  # where ingested result Parquet lives; a file:// root serves reads directly
    read_root: str = ""  # projects/CPF read models live here (a file:// or plain path root, per tenant)
    # Published OSP model snapshots the wizard's real-data templates import; empty = the repo's golden fixtures.
    reference_models_dir: str = ""
    # Keycloak OIDC (T-06 / D10); auth is enabled when the JWKS URL is set.
    oidc_jwks_url: str | None = None
    oidc_issuer: str | None = None
    oidc_audience: str = "modeler-api"
    # DEV ONLY: when true, a fixed development principal is accepted for any bearer token, so the web app can
    # run against live read APIs without Keycloak. Never enable outside local development.
    dev_auth: bool = False
    # Browser origins allowed to call the API directly (the web app's client-side writes are cross-origin).
    # Comma-separated; when empty and dev_auth is on, any localhost origin is allowed.
    cors_origins: str = ""
    # The engine image a MAP generated by the API records (MODELER_IMAGE_DIGEST); the zero digest means "not set".
    image_digest: str = "sha256:" + "0" * 64
    # Where the server's service logs live, for the project doctor (MODELER_LOGS; empty: ~/modeler-logs).
    logs: str = ""


@lru_cache
def _from_environment() -> Settings:
    return Settings()


_override: Settings | None = None


def get_settings() -> Settings:
    """The API's configuration: the only place the API reads the environment (MODELER_*, once per process).

    Routers receive it by injection (`SettingsDep`); the few helpers below a view that still call this directly see the
    same object. Tests replace it for both through `use_settings`, never by patching a router module."""
    return _override if _override is not None else _from_environment()


def reload_settings() -> None:
    """Read the environment again on the next `get_settings()` (after a test or a CLI changed MODELER_*)."""
    _from_environment.cache_clear()


@contextmanager
def use_settings(settings: Settings) -> Iterator[Settings]:
    """Run with `settings` in place of the environment's, for injected and direct reads alike."""
    global _override
    previous, _override = _override, settings
    try:
        yield settings
    finally:
        _override = previous


SettingsDep = Annotated[Settings, Depends(get_settings)]
